# Change these first
owner: MarcoMadera # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Marco Madera
    url: https://marcomadera.com
  - name: Rindu
    url: https://rindu.marcomadera.com
  - name: Dashboard
    url: https://dashboard.marcomadera.com
  - name: Authentication
    url: https://auth.marcomadera.com
  - name: Rindu Coverage
    url: https://coverage.rindu.marcomadera.com
  - name: Base API
    url: https://api.marcomadera.com
  - name: Lyrics API
    url: https://api.marcomadera.com/synced-lyrics
    expectedStatusCodes:
      - 200
      - 201
      - 401
assignees: # Users to assign downtime issues (optional)
  - MarcoMadera

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.marcomadera.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/MarcoMadera/Blog/master/public/icon_256x256.png
  name: Marco Madera
  introTitle: "Status"
  introMessage: "This page shows the status of all my services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: WebSite
      href: https://marcomadera.com
  metaTags:
    - name: "color-scheme"
      content: "dark"
  theme: dark
  themeUrl: https://cdn.statically.io/gh/MarcoMadera/status/master/assets/my-custom-theme.css
  favicon: https://marcomadera.com/favicon-48x48.png
  faviconSvg: https://marcomadera.com/logo.svg

workflowSchedule:
  uptime: "*/3 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true

commitMessages:
  commitAuthorName: "SawBot"
  commitAuthorEmail: "sawbot@marcomadera.com"

i18n:
  footer: Visit the [GitHub repository]($REPO) to see the full history of this page.
