# Change these first
owner: MarcoMadera # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Marco Madera
    url: https://marcomadera.com
  - name: Rindu
    url: https://rindu.marcomadera.com/
assignees: # Users to assign downtime issues (optional)
  - MarcoMadera

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.marcomadera.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/MarcoMadera/Blog/master/public/icon_256x256.png
  name: Status
  introTitle: "Marco Madera services"
  introMessage: "This page shows the status of all my services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: WebSite
      href: https://marcomadera.com

workflowSchedule:
  uptime: "*/3 * * * *"
